"""create core tables

Revision ID: a0dcd4f5d9f8
Revises: 1a69c18dc3e9
Create Date: 2026-08-04 21:39:02.199442
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0dcd4f5d9f8'
down_revision: Union[str, None] = '1a69c18dc3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
